# Generated by Django 3.0.8 on 2020-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200815_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='currentBid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
